import argparse
import logging
from pathlib import Path

# This is a simple Python script designed to be called by an example shell script.
# It demonstrates receiving arguments and creating an output file.

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def main(args):
    """Parses arguments and creates a sample output file."""
    logging.info("Example target script started.")
    logging.info(f"Received arguments: {args}")

    if args.output_file:
        try:
            output_path = Path(args.output_file)
            # Ensure the directory exists
            output_path.parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, "w") as f:
                f.write(f"This file was generated by the example target script.\\n")
                f.write(f"Argument received: {args.some_argument}\\n")
            logging.info(f"Successfully created output file at: {output_path}")
        except IOError as e:
            logging.error(f"Failed to write to output file: {e}")

    logging.info("Example target script finished.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="An example Python script to be called by a shell script."
    )
    parser.add_argument(
        "--some-argument",
        type=str,
        required=True,
        help="An example argument."
    )
    parser.add_argument(
        "--output-file",
        type=str,
        help="An optional output file path."
    )
    args = parser.parse_args()
    main(args) 